### ISSUE TITLE
Inputs produced by dxCompiler

### ISSUE THREAD

**Issue by lfrancioli** [dnanexus/dxCompiler#139]
Hi,

I've imported the following pipeline with dxCompiler: https://github.com/broadinstitute/warp/blob/develop/pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl

In the original pipeline, the inputs are as follows:
```
{
  "WholeGenomeGermlineSingleSample.sample_and_unmapped_bams": {
    "sample_name": "NA12878 PLUMBING",
    "base_file_name": "NA12878_PLUMBING",
    "flowcell_unmapped_bams": [
      "gs://broad-public-datasets/NA12878_downsampled_for_testing/unmapped/H06HDADXX130110.1.ATCACGAT.20k_reads.bam",
      "gs://broad-public-datasets/NA12878_downsampled_for_testing/unmapped/H06HDADXX130110.2.ATCACGAT.20k_reads.bam",
      "gs://broad-public-datasets/NA12878_downsampled_for_testing/unmapped/H06JUADXX130110.1.ATCACGAT.20k_reads.bam"
    ],
    "final_gvcf_base_name": "NA12878_PLUMBING",
    "unmapped_bam_suffix": ".bam"
  },

  "WholeGenomeGermlineSingleSample.references": {
    "contamination_sites_ud": "gs://gcp-public-data--broad-references/hg38/v0/contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.UD",
    "contamination_sites_bed": "gs://gcp-public-data--broad-references/hg38/v0/contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.bed",
    "contamination_sites_mu": "gs://gcp-public-data--broad-references/hg38/v0/contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.mu",
    "calling_interval_list": "gs://gcp-public-data--broad-references/hg38/v0/wgs_calling_regions.hg38.interval_list",
    "reference_fasta" : {
        "ref_dict": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dict",
        "ref_fasta": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta",
        "ref_fasta_index": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai",
        "ref_alt": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.alt",
        "ref_sa": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.sa",
        "ref_amb": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.amb",
        "ref_bwt": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.bwt",
        "ref_ann": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.ann",
        "ref_pac": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.64.pac"
    },
    "known_indels_sites_vcfs": [
      "gs://gcp-public-data--broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz",
      "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.known_indels.vcf.gz"
    ],
    "known_indels_sites_indices": [
      "gs://gcp-public-data--broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi",
      "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.known_indels.vcf.gz.tbi"
    ],
    "dbsnp_vcf": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf",
    "dbsnp_vcf_index": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf.idx",
    "evaluation_interval_list": "gs://gcp-public-data--broad-references/hg38/v0/wgs_evaluation_regions.hg38.interval_list",
    "haplotype_database_file": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.haplotype_database.txt"
  },

  "WholeGenomeGermlineSingleSample.scatter_settings": {
    "haplotype_scatter_count": 10,
    "break_bands_at_multiples_of": 100000
  },

  "WholeGenomeGermlineSingleSample.fingerprint_genotypes_file": "gs://broad-gotc-test-storage/single_sample/plumbing/bams/G96830.NA12878/G96830.NA12878.hg38.reference.fingerprint.vcf.gz",
  "WholeGenomeGermlineSingleSample.fingerprint_genotypes_index": "gs://broad-gotc-test-storage/single_sample/plumbing/bams/G96830.NA12878/G96830.NA12878.hg38.reference.fingerprint.vcf.gz.tbi",
  "WholeGenomeGermlineSingleSample.wgs_coverage_interval_list": "gs://gcp-public-data--broad-references/hg38/v0/wgs_coverage_regions.hg38.interval_list",

  "WholeGenomeGermlineSingleSample.papi_settings": {
    "preemptible_tries": 3,
    "agg_preemptible_tries": 3
  }
}
```

The common inputs produced are:
```
Inputs:
 stage-common
  stage-common.fingerprint_genotypes_file: [-istage-common.fingerprint_genotypes_file=(file)]

  stage-common.fingerprint_genotypes_index: [-istage-common.fingerprint_genotypes_index=(file)]

  stage-common.papi_settings: -istage-common.papi_settings=(hash)

  stage-common.papi_settings___dxfiles: [-istage-common.papi_settings___dxfiles=(file) [-istage-common.papi_settings___dxfiles=... [...]]]

  stage-common.provide_bam_output: [-istage-common.provide_bam_output=(boolean, default=false)]

  stage-common.references: -istage-common.references=(hash)

  stage-common.references___dxfiles: [-istage-common.references___dxfiles=(file) [-istage-common.references___dxfiles=... [...]]]

  stage-common.sample_and_unmapped_bams: -istage-common.sample_and_unmapped_bams=(hash)

  stage-common.sample_and_unmapped_bams___dxfiles: [-istage-common.sample_and_unmapped_bams___dxfiles=(file) [-istage-common.sample_and_unmapped_bams___dxfiles=... [...]]]

  stage-common.scatter_settings: -istage-common.scatter_settings=(hash)

  stage-common.scatter_settings___dxfiles: [-istage-common.scatter_settings___dxfiles=(file) [-istage-common.scatter_settings___dxfiles=... [...]]]

  stage-common.use_gatk3_haplotype_caller: [-istage-common.use_gatk3_haplotype_caller=(boolean, default=true)]

  stage-common.wgs_coverage_interval_list: -istage-common.wgs_coverage_interval_list=(file)
```

I've looked in the documentation but it's unclear how the parameters that now take a `hash` and a `file` (e.g. `stage-common.references`, `stage-common.references___dxfiles`) should be entered; can you provide some guidance?
